# #####################################################################
# Automatically generated by qmake (2.01a) Thu Aug 23 01:42:02 2007
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    include \
    src \
    ui 
   
INCLUDEPATH += . \
    include \
	ui
   
CONFIG += release
QT += qt3support


# Input
HEADERS += include/finddialog.h \
    include/iconprovider.h \
    include/myprocess.h \
    include/aboutgrogui.h \
    include/addpopupitem.h \
    include/commands.h \
    include/dirbrowser.h \
    include/editor.h \
    include/executor.h \
    include/groguihelp.h \
    include/logger.h \
    include/mainwindow.h \
    include/mdichild.h \
    include/mdpconfig.h \
    include/mdphighlighter.h \
    include/qconsole.h \
    include/setting.h \
    include/myprocess.h\
    ui/ui_finddialog.h \ 
    ui/ui_aboutgrogui.h \
    ui/ui_addpopupitem.h \
    ui/ui_commands.h \
    ui/ui_dirbrowser.h \
    ui/ui_executor.h \
    ui/ui_groguihelp.h \
    ui/ui_mainwindow.h \
    ui/ui_mdpconfig.h \
    ui/ui_qconsole.h \
    ui/ui_setting.h
SOURCES += src/finddialog.cpp \
    src/iconprovider.cpp \
    src/aboutgrogui.cpp \
    src/addpopupitem.cpp \
    src/commands.cpp \
    src/dirbrowser.cpp \
    src/editor.cpp \
    src/executor.cpp \
    src/groguihelp.cpp \
    src/logger.cpp \
    src/main.cpp \
    src/mainwindow.cpp \
    src/mdichild.cpp \
    src/mdphighlighter.cpp \
    src/mdpconfig.cpp \
    src/qconsole.cpp \
    src/setting.cpp
RESOURCES += src/main.qrc \
    src/mdi.qrc \
    ui/main.qrc \
    ui/mdi.qrc
